runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /js
  static_dir: templates/js

- url: /img
  static_dir: templates/img

- url: /css
  static_dir: templates/css

- url: /q/?.*
  script: q.app

- url: /vote/.*
  script: vote.app

- url: /.*
  script: main.app

- url: /_ah/bounce
  script: handle_bounced_email.app
  login: admin

libraries:
- name: jinja2
  version: latest
- name: markupsafe
  version: latest
  
inbound_services:
- mail_bounce
