application: elections-test
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /js
  static_dir: templates/js

- url: /img
  static_dir: templates/img

- url: /css
  static_dir: templates/css

- url: /vote/.*
  script: vote.app

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
